services:
  petclinic:
    image: spring-petclinic
    build: .
    expose:
      - "8080"
    deploy:
      replicas: 1
  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - petclinic
